<?php

use PHPUnit\Framework\TestCase;
use Slash\Collections;

class CollectionsTest extends TestCase {

    /**
     * The instance of Arrays.
     *
     * @var Collections
     */
    protected $collections;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->collections = New Collections();
    }

    /**
     * @dataProvider cases
     */
    public function testFunctionMethods($list, $func, $method, $experted)
    {
        $this->assertEquals($experted, call_user_func([$this->collections, $method], $list, $func));
    }

    /**
     * @dataProvider valueCases
     */
    public function testArrayMethods($list, $method, $experted)
    {
        $this->assertEquals($experted, call_user_func([$this->collections, $method], $list));
    }

    public function cases()
    {
        return [
            'With array test map' => [
                'list' => [1,2,3,4,5,6,7,8,9,10],
                'func' => function ($n) { return $n * 2; },
                'method' => 'map',
                'experted' => [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
            ],
            'With 2,4,8 return true for even' => [
                'list' => [2,4,8],
                'func' => function($number) { return Slash\isEven($number); },
                'method' => 'any',
                'experted' => true,
            ],
            'With 2,4,8 return true for even all' => [
                'list' => [2,4,8],
                'func' => function($number) { return Slash\isEven($number); },
                'method' => 'all',
                'experted' => true,
            ],
            'With 2,4,8 return [4,8] for reject 2' => [
                'list' => [2,4,8],
                'func' => function($number) { return Slash\equal($number, 2); },
                'method' => 'reject',
                'experted' => [4,8],
            ],
            'With ["a" => 2, "b" => 4, "c" => 8] pluck 0 should returns [2]' => [
                'list' => [["a" => 2], "b" => 4, "c" => 8],
                'func' => "a",
                'method' => 'pluck',
                'experted' => [2],
            ],
            'With 2,4,8 return true for even contains' => [
                'list' => [2,4,8],
                'func' => 2,
                'method' => 'contains',
                'experted' => true,
            ],
            'With array test invoke' => [
                'list' => [1,2,3,4,5,6,7,8,9,10],
                'func' => function ($n) { return $n * 2; },
                'method' => 'invoke',
                'experted' => [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
            ],
            'With array test reduce' => [
                'list' => [1,2,3],
                'func' => function ($total, $n) { return $total + $n; },
                'method' => 'reduce',
                'experted' => 6,
            ],
            'With array test sortBy' => [
                'list' => [1,4,2,3],
                'func' => function ($a, $b) { return $a < $b ? 1 : 0; },
                'method' => 'sortBy',
                'experted' => [4,3,2,1],
            ],
        ];
    }

    public function valueCases()
    {
        return [
            'With array [1, 2] size method should return 2' => [
                'list' => [1,2],
                'method' => 'size',
                'experted' => 2,
            ],
            'With null size method should returns null' => [
                'list' => null,
                'method' => 'size',
                'experted' => null,
            ],
            'With array shuffle method should returns array' => [
                'list' => [1],
                'method' => 'shuffle',
                'experted' => [1],
            ],
            'With array [1, 2] min method should return 1' => [
                'list' => [1,2],
                'method' => 'min',
                'experted' => 1,
            ],
            'With array [1, 2] max method should return 2' => [
                'list' => [1,2],
                'method' => 'max',
                'experted' => 2,
            ],
        ];
    }

    public function testToArray()
    {
        $data = 'Hello';
        $experted = [$data];
        $this->assertEquals($experted, $this->collections->toArray($data));
    }

    public function testEach()
    {
        $experted = [2,3,4,5,6,7,8,9,10,11];
        $data = [1,2,3,4,5,6,7,8,9,10];
        $actual = [];
        $this->collections->each($data, function ($n) use($actual) {
            $n++;
        });

        $this->assertEquals($experted[3], $data[3] + 1);
    }

    public function testGroupByID()
    {
        $grouped = $this->collections->groupBy([
            ['id' => 1, 'value1' => 5, 'value2' => 10],
            ['id' => 2, 'value1' => 50, 'value2' => 100],
            ['id' => 1, 'value1' => 2, 'value2' => 2],
            ['id' => 2, 'value1' => 15, 'value2' => 20],
            ['id' => 3, 'value1' => 15, 'value2' => 20],
        ], 'id');
        $expected = [
            1 => [ [ "id" => 1, "value1" => 5, "value2" => 10 ], [ "id" => 1, "value1" => 1, "value2" => 2 ] ],
            2 => [ [ "id" => 2, "value1" => 50, "value2" => 100 ], [ "id" => 2, "value1" => 15, "value2" => 20 ] ],
            3 => [ [ "id" => 3, "value1" => 15, "value2" => 20 ] ]
        ];

        $this->assertEquals($expected[3], $grouped[3]);
    }
}
