<?php

use PHPUnit\Framework\TestCase;
use Slash\Objects;

class ObjectsTest extends TestCase {

    /**
     * The instance of Utilities.
     *
     * @var Objects
     */
    protected $objects;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->objects = New Objects();
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('cases')]
    public function testFunctionMethods(\stdClass|int $list, \Closure|string|\stdClass|int|array $func, string $method, \stdClass|bool $expected): void
    {
        $this->assertEquals($expected, call_user_func([$this->objects, $method], $list, $func));
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('valueCases')]
    public function testArrayMethods(\stdClass|int|\DateTime|string|bool|\Closure|array|null $list, string $method, \stdClass|bool|array $expected): void
    {
        $this->assertEquals($expected, call_user_func([$this->objects, $method], $list));
    }

    public static function cases(): array
    {
        $obj = new \stdClass;
        $obj->foo = 'bar';
        return [
            'With apply' => [
                'list' => new \stdClass,
                'func' => function($object): void {
                    $object->foo = 'bar';
                },
                'method' => 'apply',
                'expected' => $obj,
            ],
            'With  has' => [
                'list' => new \stdClass,
                'func' => 'foo',
                'method' => 'has',
                'expected' => false,
            ],
            'With  extend' => [
                'list' => (object) ['a' => 1, 'b' => 2],
                'func' => (object) ['c' => 3, 'd' => 4],
                'method' => 'extend',
                'expected' => (object) ['c' => 3, 'd' => 4, 'a' => 1, 'b' => 2],
            ],
            'With  defaults' => [
                'list' => (object) ['a' => 1, 'b' => 2],
                'func' => (object) ['c' => 3, 'd' => 4],
                'method' => 'defaults',
                'expected' => (object) ['a' => 1, 'b' => 2],
            ],
            'With array defaults' => [
                'list' => (object) ['a' => 1, 'b' => 2],
                'func' => [(object) ['c' => 3], (object) ['d' => 4]],
                'method' => 'defaults',
                'expected' => (object) ['a' => 1, 'b' => 2],
            ],
            'With isEqual' => [
                'list' => 1,
                'func' => 1,
                'method' => 'isEqual',
                'expected' => true,
            ],
            'With not isEqual' => [
                'list' => 1,
                'func' => 0,
                'method' => 'isEqual',
                'expected' => false,
            ],
        ];
    }

    public static function valueCases(): array
    {
        return [
            'With keys' => [
                'list' => (object) ['a' => 1, 'b' => 2],
                'method' => 'keys',
                'expected' => ['a','b']
            ],
            'With values' => [
                'list' => (object) ['a' => 1, 'b' => 2],
                'method' => 'values',
                'expected' => [1,2]
            ],
            'With copy' => [
                'list' => (object) ['a' => 1, 'b' => 2],
                'method' => 'copy',
                'expected' => (object) ['a' => 1, 'b' => 2]
            ],
            'With isNull' => [
                'list' => null,
                'method' => 'isNUll',
                'expected' => true
            ],
            'With isNull false' => [
                'list' => 1,
                'method' => 'isNUll',
                'expected' => false
            ],
            'With array isTraversable' => [
                'list' => [],
                'method' => 'isTraversable',
                'expected' => true
            ],
            'With null isTraversable' => [
                'list' => null,
                'method' => 'isTraversable',
                'expected' => false
            ],
            'With array isArray' => [
                'list' => [],
                'method' => 'isArray',
                'expected' => true
            ],
            'With  isDate' => [
                'list' => new DateTime,
                'method' => 'isDate',
                'expected' => true
            ],
            'With not isDate' => [
                'list' => new stdClass,
                'method' => 'isDate',
                'expected' => false
            ],
            'With not isNumber' => [
                'list' => '',
                'method' => 'isNumber',
                'expected' => false
            ],
            'With  isNumber' => [
                'list' => 1,
                'method' => 'isNumber',
                'expected' => true
            ],
            'With not isBoolean' => [
                'list' => new stdClass,
                'method' => 'isBoolean',
                'expected' => false
            ],
            'With isBoolean' => [
                'list' => true,
                'method' => 'isBoolean',
                'expected' => true
            ],
            'With  isString' => [
                'list' => '',
                'method' => 'isString',
                'expected' => true
            ],
            'With not  isString' => [
                'list' => true,
                'method' => 'isString',
                'expected' => false
            ],
            'With  isFunction' => [
                'list' => function(): void {},
                'method' => 'isFunction',
                'expected' => true
            ],
            'With not isFunction' => [
                'list' => true,
                'method' => 'isFunction',
                'expected' => false
            ],
            'With isObject' => [
                'list' => new stdClass,
                'method' => 'isObject',
                'expected' => true
            ],
            'With not isObject' => [
                'list' => true,
                'method' => 'isObject',
                'expected' => false
            ],
            'With not isEmpty' => [
                'list' => true,
                'method' => 'isEmpty',
                'expected' => false
            ],
            'With isEmpty' => [
                'list' => [],
                'method' => 'isEmpty',
                'expected' => true
            ],
        ];
    }

    function testMethods(): void
    {
        $methods = $this->objects->methods(new DummyMethods3());
        $this->assertEquals(['foo'], $methods);
        $this->expectException('ReflectionException');
        $this->objects->methods('bar');

    }
}

class DummyMethods3 {

    public function foo($var = 'wow')
    {
        return $var;
    }

}
