<?php

use PHPUnit\Framework\TestCase;
use Slash\Utilities;

class UtilitiesTest extends TestCase {

    /**
     * The instance of Utilities.
     *
     * @var Utilities
     */
    protected $utilities;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->utilities = New Utilities();
    }

    #[\PHPUnit\Framework\Attributes\DataProvider('valueCases')]
    public function testArrayMethods(string|int $list, string $method, string|int $expected): void
    {
        $this->assertEquals($expected, call_user_func([$this->utilities, $method], $list));
    }

    public static function valueCases(): array
    {
        return [
            'With escape' => [
                'list' => '<h1>Hello world</h1>',
                'method' => 'escape',
                'expected' => htmlentities('<h1>Hello world</h1>', ENT_QUOTES, 'UTF-8', false),
            ],
            'With with' => [
                'list' => 1,
                'method' => 'with',
                'expected' => 1,
            ],
        ];
    }

    public function testToArray(): void
    {
        $this->utilities->id('test');
        $this->utilities->times(2, function (): void { });
        $this->assertTrue(true);
    }
}
