<?php

use PHPUnit\Framework\TestCase;
use Slash\Utilities;

class UtilitiesTest extends TestCase {

    /**
     * The instance of Utilities.
     *
     * @var Utilities
     */
    protected $utilities;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->utilities = New Utilities();
    }

    /**
     * @dataProvider valueCases
     */
    public function testArrayMethods($list, $method, $experted)
    {
        $this->assertEquals($experted, call_user_func([$this->utilities, $method], $list));
    }

    public function valueCases()
    {
        return [
            'With escape' => [
                'list' => '<h1>Hello world</h1>',
                'method' => 'escape',
                'experted' => htmlentities('<h1>Hello world</h1>', ENT_QUOTES, 'UTF-8', false),
            ],
            'With with' => [
                'list' => 1,
                'method' => 'with',
                'experted' => 1,
            ],
        ];
    }

    public function testToArray()
    {
        $this->utilities->id('test');
        $this->utilities->times(2, function () { });
        $this->assertTrue(true);
    }
}
